const crypto = require('crypto');

console.log('🔐 Generating secure secrets for Railway deployment...\n');

// Generate secure random secrets
const jwtSecret = crypto.randomBytes(32).toString('hex');
const hmacSecret = crypto.randomBytes(32).toString('hex');
const secretVaultKey = crypto.randomBytes(32).toString('hex');

console.log('Copy these environment variables to your Railway project:\n');
console.log('='.repeat(60));
console.log('REQUIRED ENVIRONMENT VARIABLES FOR RAILWAY:');
console.log('='.repeat(60));
console.log();

console.log('# Security Secrets (REQUIRED)');
console.log(`JWT_SECRET=${jwtSecret}`);
console.log(`HMAC_SECRET=${hmacSecret}`);
console.log(`SECRET_VAULT_KEY=${secretVaultKey}`);
console.log();

console.log('# Application Configuration (REQUIRED)');
console.log('NODE_ENV=production');
console.log('# PORT is automatically set by Railway');
console.log('FRONTEND_URL=https://your-frontend-domain.netlify.app');
console.log();

console.log('# Database (Railway will provide this automatically)');
console.log('# DATABASE_URL=postgresql://... (auto-generated by Railway)');
console.log();

console.log('# Supabase Configuration (from your env.example)');
console.log('SUPABASE_URL=https://vqufkqgrxrjmjrgpcscv.supabase.co');
console.log('SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxdWZrcWdyeHJqbWpyZ3Bjc2N2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2ODA5ODEsImV4cCI6MjA3MDI1Njk4MX0.lb_jeVSkIYPmMpBOofEwjni8OpHazEhTNZzBOx0wwAI');
console.log();

console.log('='.repeat(60));
console.log('NEXT STEPS:');
console.log('='.repeat(60));
console.log('1. Go to your Railway project dashboard');
console.log('2. Click on your backend service');
console.log('3. Go to the "Variables" tab');
console.log('4. Add each environment variable above');
console.log('5. Make sure to add a PostgreSQL database service');
console.log('6. Redeploy your service');
console.log();
console.log('🚀 Your backend should work after setting these variables!');
