[build]
builder = "DOCKERFILE"
dockerfilePath = "railway.dockerfile"

[deploy]
startCommand = "/app/entrypoint.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
