[build]
builder = "dockerfile"
dockerfilePath = "railway.dockerfile"
watchPaths = ["backend/**"]

[deploy]
startCommand = "/app/start.sh"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
